trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'windows-2019'

  azureServiceConnection: 'TestSubDeployment'
  resourceGroupName: 'v-jeremyrTestCase2402120030001367'
  templateFile: 'main.bicep'

parameters:
- name: 'regions'
  type: object
  default: [
    'EASTUS',
    'NORTHEUROPE',
    'WESTUS'
  ]

pool:
  vmImage: $(vmImageName)

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureServiceConnection)
    azurePowerShellVersion: LatestVersion
    scriptType: 'InlineScript'
    Inline: |
      $regionsArr = '${{ convertToJson(parameters.regions) }}' | ConvertFrom-Json;
      foreach ($region in $regionsArr)
      {
        New-AzResourceGroupDeployment -Name DevOpsRun_$region -ResourceGroupName $(resourceGroupName) -TemplateFile $(templateFile) -TemplateParameterFile parameters/main_$region.parameters.json
      }
