trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'windows-2019'

  azureServiceConnection: 'TestSubDeployment'
  resourceGroupName: 'v-jeremyrTestCase2402120030001367'
  templateFile: 'main.bicep'
  parametersFiles: 'parameters/main1.parameters.json parameters/main2.parameters.json parameters/main3.parameters.json'
  singleParameterFile: 'parameters/main1.parameters.json'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureServiceConnection)
    azurePowerShellVersion: LatestVersion
    scriptType: 'InlineScript'
    Inline: |
      $i = 1
      $parametersFilesArr = $(parametersFiles).Split(" ")
      foreach ($parametersFile in $parametersFilesArr)
      {
        New-AzResourceGroupDeployment -Name DevOpsRun$i -ResourceGroupName $(resourceGroupName) -TemplateFile $(templateFile) -TemplateParameterFile $parametersFile
      }
